version: '3.8'

services:
  # --- 1. POSTGRESQL (DATABASE UTAMA) ---
  db:
    image: postgres:15-alpine
    container_name: mkn_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pemetaankemiskinan_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- 2. MINIO (GUDANG FOTO TIPE S3) ---
  minio:
    image: minio/minio
    container_name: mkn_minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin_minio
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata: